PORT: ${PORT}

POSTGRES_HOST: ${POSTGRES_HOST}
POSTGRES_PORT: ${POSTGRES_PORT}
POSTGRES_USER: ${POSTGRES_USER}
POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}

REDIS_ADDR: ${REDIS_ADDR}
REDIS_PASS: ${REDIS_PASS}

RABBIT_MQ_USER: ${RABBIT_MQ_USER}
RABBIT_MQ_PASSWORD: ${RABBIT_MQ_PASSWORD}
RABBIT_MQ_HOST: ${RABBIT_MQ_HOST}
RABBIT_MQ_PORT: ${RABBIT_MQ_PORT}
RABBIT_MQ_VHOST: ${RABBIT_MQ_VHOST}
RABBIT_MQ_QUEUE: ${RABBIT_MQ_QUEUE}
RABBIT_MQ_EXCHANGE: ${RABBIT_MQ_EXCHANGE}
RABBIT_MQ_ROUTING_KEY: ${RABBIT_MQ_ROUTING_KEY}

KEYCLOAK_URL: ${KEYCLOAK_URL}
KEYCLOAK_REALM: ${KEYCLOAK_REALM}

