PORT: ${PORT}

POSTGRES_HOST: ${POSTGRES_HOST}
POSTGRES_PORT: ${POSTGRES_PORT}
POSTGRES_USER: ${POSTGRES_USER}
POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}

REDIS_ADDR: ${REDIS_ADDR}
REDIS_PASS: ${REDIS_PASS}

KAFKA_BROKERS:
  - ${KAFKA_BROKERS}
KAFKA_TOPIC: ${KAFKA_TOPIC}

KEYCLOAK_URL: ${KEYCLOAK_URL}
KEYCLOAK_REALM: ${KEYCLOAK_REALM}

